-- MySQL Script generated by MySQL Workbench
-- 06/22/15 04:39:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sharedpen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sharedpen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sharedpen` DEFAULT CHARACTER SET latin1 ;
USE `sharedpen` ;

-- -----------------------------------------------------
-- Table `sharedpen`.`Agrupamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Agrupamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `password` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `avatar` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `active` VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 311
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Escola` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `morada` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `contacto` INT(9) NULL DEFAULT NULL COMMENT '',
  `id_agrupamento` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Escola_ibfk_1` (`id_agrupamento` ASC)  COMMENT '',
  CONSTRAINT `Escola_ibfk_1`
    FOREIGN KEY (`id_agrupamento`)
    REFERENCES `sharedpen`.`Agrupamento` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Aluno` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `nome` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `turma` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `ano` INT(11) NOT NULL COMMENT '',
  `id_escola` INT(11) NOT NULL COMMENT '',
  `num_aluno` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '',
  INDEX `asdas_idx` (`id_escola` ASC)  COMMENT '',
  CONSTRAINT `Aluno_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`),
  CONSTRAINT `Aluno_ibfk_11`
    FOREIGN KEY (`id_escola`)
    REFERENCES `sharedpen`.`Escola` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`modelos_pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`modelos_pagina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(20) NOT NULL COMMENT '',
  `htmltext` TEXT NOT NULL COMMENT '',
  `icon` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`modelo` (
  `idmodelo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_livro` VARCHAR(50) NOT NULL COMMENT '',
  `num_modeloCapa` INT(11) NOT NULL COMMENT '',
  `num_modeloPagina` INT(11) NOT NULL COMMENT '',
  `html_texto` TEXT NULL DEFAULT NULL COMMENT '',
  `css_texto` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idmodelo`)  COMMENT '',
  INDEX `num_modeloCapa` (`num_modeloCapa` ASC)  COMMENT '',
  INDEX `num_modeloPagina` (`num_modeloPagina` ASC)  COMMENT '',
  CONSTRAINT `modelo_ibfk_1`
    FOREIGN KEY (`num_modeloCapa`)
    REFERENCES `sharedpen`.`modelos_pagina` (`id`),
  CONSTRAINT `modelo_ibfk_2`
    FOREIGN KEY (`num_modeloPagina`)
    REFERENCES `sharedpen`.`modelos_pagina` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Projectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Projectos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `id_creator` INT(11) NULL DEFAULT NULL COMMENT '',
  `tipo` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `id_modelo` INT(11) NULL DEFAULT NULL COMMENT '',
  `estado` TINYINT(1) NULL DEFAULT '1' COMMENT '',
  `array` LONGTEXT NULL DEFAULT NULL COMMENT '',
  `texto` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `id_modelo`
    FOREIGN KEY (`id`)
    REFERENCES `sharedpen`.`modelo` (`idmodelo`)
    )
ENGINE = InnoDB
AUTO_INCREMENT = 190
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Avaliacao` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `id_projecto` INT(11) NOT NULL COMMENT '',
  `avaliacao` VARCHAR(2) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  INDEX `id_user` (`id_user` ASC)  COMMENT '',
  INDEX `id_projecto` (`id_projecto` ASC)  COMMENT '',
  CONSTRAINT `Avaliacao_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`),
  CONSTRAINT `Avaliacao_ibfk_2`
    FOREIGN KEY (`id_projecto`)
    REFERENCES `sharedpen`.`Projectos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`ExcellDados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`ExcellDados` (
  `ExcellDados_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Pauta` VARCHAR(5) NOT NULL COMMENT '',
  `Curso` VARCHAR(5) NULL DEFAULT NULL COMMENT '',
  `Numero` VARCHAR(5) NULL DEFAULT NULL COMMENT '',
  `Nome` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Data` VARCHAR(5) NULL DEFAULT NULL COMMENT '',
  `---` VARCHAR(5) NULL DEFAULT NULL COMMENT '',
  `Inscrito` VARCHAR(12) NULL DEFAULT NULL COMMENT '',
  `Inscritoa` VARCHAR(12) NULL DEFAULT NULL COMMENT '',
  `T` VARCHAR(12) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ExcellDados_id`)  COMMENT '')
ENGINE = MyISAM
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Externo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Externo` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `nome` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `id_refer` INT(11) NOT NULL COMMENT '',
  INDEX `id_user` (`id_user` ASC)  COMMENT '',
  INDEX `id_refer` (`id_refer` ASC)  COMMENT '',
  CONSTRAINT `Externo_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`),
  CONSTRAINT `Externo_ibfk_2`
    FOREIGN KEY (`id_refer`)
    REFERENCES `sharedpen`.`User` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Professor` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `nome` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '',
  `id_agrupamento` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '',
  INDEX `Professor_ibfk_1` (`id_agrupamento` ASC)  COMMENT '',
  CONSTRAINT `fk_{100AB46E-61C6-442F-B1BB-4FAA6F2F78EA}`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Professor_ibfk_1`
    FOREIGN KEY (`id_agrupamento`)
    REFERENCES `sharedpen`.`Agrupamento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`Roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `pagesView` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`UserContributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`UserContributo` (
  `idProjeto` INT(11) NOT NULL COMMENT '',
  `idUser` INT(11) NOT NULL COMMENT '',
  `pagina` VARCHAR(25) NOT NULL COMMENT '',
  `editor` VARCHAR(25) NOT NULL COMMENT '',
  `contributo` TEXT NULL DEFAULT NULL COMMENT '',
  INDEX `idUser_idx` (`idUser` ASC)  COMMENT '',
  INDEX `idProjeto_idx` (`idProjeto` ASC)  COMMENT '',
  CONSTRAINT `idProjeto`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `sharedpen`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `sharedpen`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`UserEscolas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`UserEscolas` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `id_escola` INT(11) NOT NULL COMMENT '',
  INDEX `id_user` (`id_user` ASC)  COMMENT '',
  INDEX `id_escola` (`id_escola` ASC)  COMMENT '',
  CONSTRAINT `UserEscolas_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`),
  CONSTRAINT `UserEscolas_ibfk_2`
    FOREIGN KEY (`id_escola`)
    REFERENCES `sharedpen`.`Escola` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`UsersProject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`UsersProject` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `id_proj` INT(11) NOT NULL COMMENT '',
  INDEX `id_user` (`id_user` ASC)  COMMENT '',
  INDEX `id_proj` (`id_proj` ASC)  COMMENT '',
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_proj`
    FOREIGN KEY (`id_proj`)
    REFERENCES `sharedpen`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sharedpen`.`UsersRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharedpen`.`UsersRoles` (
  `id_user` INT(11) NOT NULL COMMENT '',
  `id_role` INT(11) NOT NULL COMMENT '',
  INDEX `id_user` (`id_user` ASC)  COMMENT '',
  INDEX `id_role` (`id_role` ASC)  COMMENT '',
  CONSTRAINT `UsersRoles_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sharedpen`.`User` (`id`),
  CONSTRAINT `UsersRoles_ibfk_2`
    FOREIGN KEY (`id_role`)
    REFERENCES `sharedpen`.`Roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
